In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv(r'C:\Users\ssrin\Workspace\Code\Upright_edu\wk8-stores.csv')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   store_id      15 non-null     int64
 1   store_name    15 non-null     str
 2   address       15 non-null     str
 3   city          15 non-null     str
 4   state         15 non-null     str
 5   zip_code      15 non-null     str
 6   region        15 non-null     str
 7   size_sqft     13 non-null     float64
 8   opening_date  14 non-null     str
dtypes: float64(1), int64(1), str(7)
memory usage: 1.2 KB

In [4]:
df.describe()

        store_id     size_sqft
count  15.000000     13.000000
mean    8.000000  30653.846154
std     4.472136  11342.002717
min     1.000000  16500.000000
25%     4.500000  22000.000000
50%     8.000000  29000.000000
75%    11.500000  35000.000000
max    15.000000  55000.000000

In [5]:
df

,store_id,store_name,address,city,state,zip_code,region,size_sqft,opening_date
0,1,City Center,123 Retail Blvd,New York,NY,10001,Northeast,32500.0,2005-05-20
1,2,Mall of Chicago,456 Shopping Ave,Chicago,IL,60611,Midwest,45000.0,2007-08-15
2,3,Los Angeles Plaza,789 Commerce St,Los Angeles,CA,90001,West,55000.0,2004-03-10
3,4,Houston Galleria,321 Main St,Houston,Texas,77002,Southwest,NaN,2008-11-05
4,5,Phoenix Outlet,654 Desert Rd,Phoenix,AZ,85001,Southwest,18500.0,2010-06-30
5,6,Philadelphia Center,987 Market St,Philadelphia,PA,19103,Northeast,22000.0,2009-09-12
6,7,San Antonio Mall,741 River Walk,San Antonio,TX,78205,Southwest,35000.0,2012-04-22
7,8,San Diego Plaza,852 Pacific Hwy,San Diego,CA,92101,West,27500.0,2006-07-18
8,9,Dallas Galleria,963 Lone Star Blvd,Dallas,TX,75201-5555,Southwest,42000.0,NaN
9,10,Boston Outlet,159 Freedom Rd,Boston,Massachusetts,02108,Northeast,16500.0,2014-10-09
10,11,Seattle City Center,753 Rainy St,Seattle,WA,98101,West,29000.0,2011-02-14
11,12,Denver Mountain Mall,951 Mile High Dr,Denver,CO,80202,West,31500.0,2015-08-27
12,13,Miami Beach Plaza,357 Ocean Dr,Miami,FL,33139,Southeast,24000.0,2016-12-03
13,14,Minneapolis Galleria,852 Lake St,Minneapolis,MN,55401,Midwest,NaN,2013-05-11
14,15,Atlanta Outlet,456 Peachtree St,Atlanta,Georgia,30303,Southeast,20000.0,2018-09-25

In [6]:
df.isnull().sum()

store_id        0
store_name      0
address         0
city            0
state           0
zip_code        0
region          0
size_sqft       2
opening_date    1
dtype: int64

In [7]:
df['size_sqft']=df['size_sqft'].fillna(35000.0)

In [10]:
df['opening_date']=df['opening_date'].ffill()

In [13]:
df['state']=df['state'].replace('Texas','TX')
df['state']=df['state'].replace('Massachusetts','MA')
df['state']=df['state'].replace('Georgia','GA')

In [14]:
df

,store_id,store_name,address,city,state,zip_code,region,size_sqft,opening_date
0,1,City Center,123 Retail Blvd,New York,NY,10001,Northeast,32500.0,2005-05-20
1,2,Mall of Chicago,456 Shopping Ave,Chicago,IL,60611,Midwest,45000.0,2007-08-15
2,3,Los Angeles Plaza,789 Commerce St,Los Angeles,CA,90001,West,55000.0,2004-03-10
3,4,Houston Galleria,321 Main St,Houston,TX,77002,Southwest,35000.0,2008-11-05
4,5,Phoenix Outlet,654 Desert Rd,Phoenix,AZ,85001,Southwest,18500.0,2010-06-30
5,6,Philadelphia Center,987 Market St,Philadelphia,PA,19103,Northeast,22000.0,2009-09-12
6,7,San Antonio Mall,741 River Walk,San Antonio,TX,78205,Southwest,35000.0,2012-04-22
7,8,San Diego Plaza,852 Pacific Hwy,San Diego,CA,92101,West,27500.0,2006-07-18
8,9,Dallas Galleria,963 Lone Star Blvd,Dallas,TX,75201-5555,Southwest,42000.0,2006-07-18
9,10,Boston Outlet,159 Freedom Rd,Boston,MA,02108,Northeast,16500.0,2014-10-09
10,11,Seattle City Center,753 Rainy St,Seattle,WA,98101,West,29000.0,2011-02-14
11,12,Denver Mountain Mall,951 Mile High Dr,Denver,CO,80202,West,31500.0,2015-08-27
12,13,Miami Beach Plaza,357 Ocean Dr,Miami,FL,33139,Southeast,24000.0,2016-12-03
13,14,Minneapolis Galleria,852 Lake St,Minneapolis,MN,55401,Midwest,35000.0,2013-05-11
14,15,Atlanta Outlet,456 Peachtree St,Atlanta,GA,30303,Southeast,20000.0,2018-09-25

In [21]:
df['opening_date']=pd.to_datetime(df['opening_date'])

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   store_id      15 non-null     int64
 1   store_name    15 non-null     str
 2   address       15 non-null     str
 3   city          15 non-null     str
 4   state         15 non-null     str
 5   zip_code      15 non-null     str
 6   region        15 non-null     str
 7   size_sqft     15 non-null     float64
 8   opening_date  15 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(1), str(6)
memory usage: 1.2 KB

In [15]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.drop_duplicates()

,store_id,store_name,address,city,state,zip_code,region,size_sqft,opening_date
0,1,City Center,123 Retail Blvd,New York,NY,10001,Northeast,32500.0,2005-05-20
1,2,Mall of Chicago,456 Shopping Ave,Chicago,IL,60611,Midwest,45000.0,2007-08-15
2,3,Los Angeles Plaza,789 Commerce St,Los Angeles,CA,90001,West,55000.0,2004-03-10
3,4,Houston Galleria,321 Main St,Houston,TX,77002,Southwest,35000.0,2008-11-05
4,5,Phoenix Outlet,654 Desert Rd,Phoenix,AZ,85001,Southwest,18500.0,2010-06-30
5,6,Philadelphia Center,987 Market St,Philadelphia,PA,19103,Northeast,22000.0,2009-09-12
6,7,San Antonio Mall,741 River Walk,San Antonio,TX,78205,Southwest,35000.0,2012-04-22
7,8,San Diego Plaza,852 Pacific Hwy,San Diego,CA,92101,West,27500.0,2006-07-18
8,9,Dallas Galleria,963 Lone Star Blvd,Dallas,TX,75201-5555,Southwest,42000.0,2006-07-18
9,10,Boston Outlet,159 Freedom Rd,Boston,MA,02108,Northeast,16500.0,2014-10-09
10,11,Seattle City Center,753 Rainy St,Seattle,WA,98101,West,29000.0,2011-02-14
11,12,Denver Mountain Mall,951 Mile High Dr,Denver,CO,80202,West,31500.0,2015-08-27
12,13,Miami Beach Plaza,357 Ocean Dr,Miami,FL,33139,Southeast,24000.0,2016-12-03
13,14,Minneapolis Galleria,852 Lake St,Minneapolis,MN,55401,Midwest,35000.0,2013-05-11
14,15,Atlanta Outlet,456 Peachtree St,Atlanta,GA,30303,Southeast,20000.0,2018-09-25

In [18]:
df['store_id'].unique

<bound method Series.unique of 0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
Name: store_id, dtype: int64>

In [20]:
df.groupby('region')['size_sqft'].sum().sort_values(ascending= False)

region
West         143000.0
Southwest    130500.0
Midwest       80000.0
Northeast     71000.0
Southeast     44000.0
Name: size_sqft, dtype: float64