In [45]:
import pandas as pd
import numpy as np
df = pd.read_csv(r'C:\Users\ssrin\Workspace\Code\Upright_edu\wk8-inventory.csv')

In [46]:
df.head()

,inventory_id,store_id,product_id,quantity_in_stock,last_restock_date,reorder_level
0,1,1,1,25,2022-10-15,10.0
1,2,1,5,42,2022-11-02,15.0
2,3,1,10,18,2022-09-30,8.0
3,4,1,15,5,2022-10-20,10.0
4,5,1,20,12,NaN,15.0

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   inventory_id       75 non-null     int64
 1   store_id           75 non-null     int64
 2   product_id         75 non-null     int64
 3   quantity_in_stock  75 non-null     int64
 4   last_restock_date  66 non-null     str
 5   reorder_level      69 non-null     float64
dtypes: float64(1), int64(4), str(1)
memory usage: 3.6 KB

In [48]:
df.describe()

       inventory_id   store_id  product_id  quantity_in_stock  reorder_level
count     75.000000  75.000000   75.000000          75.000000      69.000000
mean      38.000000   8.000000   12.733333          22.640000      12.681159
std       21.794495   4.349588    7.179801          13.923187       3.327659
min        1.000000   1.000000    1.000000           0.000000       8.000000
25%       19.500000   4.000000    6.500000          15.000000      10.000000
50%       38.000000   8.000000   13.000000          25.000000      10.000000
75%       56.500000  12.000000   19.000000          33.500000      15.000000
max       75.000000  15.000000   25.000000          45.000000      20.000000

In [49]:
df.isnull().sum()

inventory_id         0
store_id             0
product_id           0
quantity_in_stock    0
last_restock_date    9
reorder_level        6
dtype: int64

In [50]:
df

,inventory_id,store_id,product_id,quantity_in_stock,last_restock_date,reorder_level
0,1,1,1,25,2022-10-15,10.0
1,2,1,5,42,2022-11-02,15.0
2,3,1,10,18,2022-09-30,8.0
3,4,1,15,5,2022-10-20,10.0
4,5,1,20,12,NaN,15.0
...,...,...,...,...,...,...
70,71,15,5,0,2022-10-16,10.0
71,72,15,10,22,2022-09-25,8.0
72,73,15,15,29,2022-11-22,10.0
73,74,15,20,0,2022-10-01,15.0
74,75,15,25,36,NaN,10.0

In [61]:
df['reorder_level']=df['reorder_level'].fillna(10.0)
df['last_restock_date']=df['last_restock_date'].ffill()

In [62]:
df

,inventory_id,store_id,product_id,quantity_in_stock,last_restock_date,reorder_level
0,1,1,1,25,2022-10-15,10.0
1,2,1,5,42,2022-11-02,15.0
2,3,1,10,18,2022-09-30,8.0
3,4,1,15,5,2022-10-20,10.0
4,5,1,20,12,2022-10-20,15.0
...,...,...,...,...,...,...
70,71,15,5,0,2022-10-16,10.0
71,72,15,10,22,2022-09-25,8.0
72,73,15,15,29,2022-11-22,10.0
73,74,15,20,0,2022-10-01,15.0
74,75,15,25,36,2022-10-01,10.0

In [63]:
df['last_restock_date']= pd.to_datetime(df['last_restock_date'])

In [64]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   inventory_id       75 non-null     int64
 1   store_id           75 non-null     int64
 2   product_id         75 non-null     int64
 3   quantity_in_stock  75 non-null     int64
 4   last_restock_date  75 non-null     datetime64[us]
 5   reorder_level      75 non-null     float64
dtypes: datetime64[us](1), float64(1), int64(4)
memory usage: 3.6 KB

In [65]:
df['inventory_id'].unique

<bound method Series.unique of 0      1
1      2
2      3
3      4
4      5
      ..
70    71
71    72
72    73
73    74
74    75
Name: inventory_id, Length: 75, dtype: int64>

In [66]:
df.duplicated().sum()

np.int64(0)

In [67]:
df.drop_duplicates()

,inventory_id,store_id,product_id,quantity_in_stock,last_restock_date,reorder_level
0,1,1,1,25,2022-10-15,10.0
1,2,1,5,42,2022-11-02,15.0
2,3,1,10,18,2022-09-30,8.0
3,4,1,15,5,2022-10-20,10.0
4,5,1,20,12,2022-10-20,15.0
...,...,...,...,...,...,...
70,71,15,5,0,2022-10-16,10.0
71,72,15,10,22,2022-09-25,8.0
72,73,15,15,29,2022-11-22,10.0
73,74,15,20,0,2022-10-01,15.0
74,75,15,25,36,2022-10-01,10.0

In [68]:
df.groupby('product_id')['quantity_in_stock'].sum().sort_values()

product_id
15     34
23     35
12     42
20     45
18     48
2      50
3      54
24     56
25     56
9      59
6      63
11     63
22     67
19     67
14     68
7      74
16     78
21     78
10     80
4      86
1      89
5      95
8      97
13    101
17    113
Name: quantity_in_stock, dtype: int64