In [64]:
import pandas as pd
import numpy as np
df = pd.read_csv(r'C:\Users\ssrin\Workspace\Code\Upright_edu\wk8-products.csv')

In [65]:
df.head()

,product_id,product_name,category,subcategory,brand,price,cost,weight
0,1,Apple iPhone 13,Electronics,Smartphones,Apple,899.99,649.99,0.45
1,2,Samsung Galaxy S21,electronics,Smartphones,Samsung,799.99,539.99,0.50
2,3,Sony WH-1000XM4,ELECTRONICS,Headphones,Sony,349.99,210.00,0.60
3,4,Dell XPS 13,Electronics,Laptops,Dell,1299.99,899.99,2.80
4,5,Nike Classic Tee,Clothing,Shirts,Nike,24.99,12.50,0.20

In [66]:
df.describe()

       product_id        price         cost     weight
count   30.000000    30.000000    30.000000  28.000000
mean    15.500000   191.724000   203.159000   3.835714
std      8.803408   452.483576   278.924138   5.693236
min      1.000000 -1599.990000     1.800000   0.200000
25%      8.250000    46.990000    28.375000   0.500000
50%     15.500000   134.990000    82.500000   1.150000
75%     22.750000   322.490000   236.250000   3.750000
max     30.000000  1299.990000  1100.000000  25.000000

In [67]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    30 non-null     int64
 1   product_name  30 non-null     str
 2   category      30 non-null     str
 3   subcategory   30 non-null     str
 4   brand         30 non-null     str
 5   price         30 non-null     float64
 6   cost          30 non-null     float64
 7   weight        28 non-null     float64
dtypes: float64(3), int64(1), str(4)
memory usage: 2.0 KB

In [68]:
df.isnull().sum()

product_id      0
product_name    0
category        0
subcategory     0
brand           0
price           0
cost            0
weight          2
dtype: int64

In [69]:
df['weight']=df['weight'].ffill()

In [70]:
df

,product_id,product_name,category,subcategory,brand,price,cost,weight
0,1,Apple iPhone 13,Electronics,Smartphones,Apple,899.99,649.99,0.45
1,2,Samsung Galaxy S21,electronics,Smartphones,Samsung,799.99,539.99,0.50
2,3,Sony WH-1000XM4,ELECTRONICS,Headphones,Sony,349.99,210.00,0.60
3,4,Dell XPS 13,Electronics,Laptops,Dell,1299.99,899.99,2.80
4,5,Nike Classic Tee,Clothing,Shirts,Nike,24.99,12.50,0.20
5,6,Levi's Slim Jeans,clothing,Pants,Levi's,59.99,31.00,0.90
6,7,KitchenAid Stand Mixer,Home & Kitchen,Kitchen Appliances,KitchenAid,349.99,245.00,10.00
7,8,Cuisinart Coffee Maker,home & kitchen,Kitchen Appliances,Cuisinart,99.99,55.00,3.50
8,9,IKEA Malm Dresser,Home and Kitchen,Furniture,IKEA,179.99,85.00,3.50
9,10,Penguin Classics Collection,Books,Fiction,Penguin,49.99,27.50,2.00
10,11,The North Face Jacket,Sports & Outdoors,Jackets,The North Face,199.99,110.00,1.30
11,12,Nike Running Shoes,sports & outdoors,Shoes,Nike,129.99,65.00,0.70
12,13,LEGO Star Wars Set,Toys,Building Toys,LEGO,89.99,45.00,1.50
13,14,L'Oreal Revitalift Cream,Beauty,Skincare,L'Oreal,19.99,8.00,0.30
14,15,Apple MacBook Pro,Electronics,Laptops,Apple,-1599.99,1100.00,3.50
15,16,Bose QuietComfort 45,Electronics,Headphones,Bose,329.99,495.00,0.50
16,17,Hershey's Chocolate Assortment,Grocery,Snacks,Hershey's,15.99,7.00,1.00
17,18,Adidas Track Pants,Clothing,Pants,Adidas,45.99,23.00,0.60
18,19,Kindle Paperwhite,ELECTRONICS,E-Readers,Amazon,139.99,80.00,0.40
19,20,Dyson V11 Vacuum,HOME & KITCHEN,Appliances,Dyson,599.99,375.00,6.70
20,21,Outdoor Gas Grill,Home & Kitchen,Outdoor,Weber,299.99,165.00,25.00
21,22,Calvin Klein Men's Shirt,Apparel,Shirts,Calvin Klein,39.99,20.00,25.00
22,23,Coleman Camping Tent,Sports and Outdoors,Camping,Coleman,149.99,75.00,8.50
23,24,Mattel Barbie Dreamhouse,Toys,Dolls,Mattel,199.99,99.00,12.00
24,25,Neutrogena Face Wash,beauty,Skincare,Neutrogena,9.99,4.00,0.35
25,26,General Mills Cereal,Food,Breakfast,General Mills,4.99,1.80,0.90
26,27,Sony PlayStation 5,Electronics,Gaming,Sony,499.99,399.00,4.50
27,28,HP Wireless Printer,electronics,Printers,HP,129.99,85.00,15.00
28,29,Zara Maxi Dress,Clothing,Dresses,Zara,79.99,32.00,0.50
29,30,Columbia Winter Parka,Sports & Outdoors,Jackets,Columbia,249.99,150.00,3.20

In [71]:

df['subcategory']=df['subcategory'].astype(dtype='category')

In [72]:
df['category'].str.title()

0             Electronics
1             Electronics
2             Electronics
3             Electronics
4                Clothing
5                Clothing
6          Home & Kitchen
7          Home & Kitchen
8        Home And Kitchen
9                   Books
10      Sports & Outdoors
11      Sports & Outdoors
12                   Toys
13                 Beauty
14            Electronics
15            Electronics
16                Grocery
17               Clothing
18            Electronics
19         Home & Kitchen
20         Home & Kitchen
21                Apparel
22    Sports And Outdoors
23                   Toys
24                 Beauty
25                   Food
26            Electronics
27            Electronics
28               Clothing
29      Sports & Outdoors
Name: category, dtype: str

In [75]:
df.duplicated().sum()

np.int64(0)

In [77]:
df.drop_duplicates()

,product_id,product_name,category,subcategory,brand,price,cost,weight
0,1,Apple iPhone 13,Electronics,Smartphones,Apple,899.99,649.99,0.45
1,2,Samsung Galaxy S21,electronics,Smartphones,Samsung,799.99,539.99,0.50
2,3,Sony WH-1000XM4,ELECTRONICS,Headphones,Sony,349.99,210.00,0.60
3,4,Dell XPS 13,Electronics,Laptops,Dell,1299.99,899.99,2.80
4,5,Nike Classic Tee,Clothing,Shirts,Nike,24.99,12.50,0.20
5,6,Levi's Slim Jeans,clothing,Pants,Levi's,59.99,31.00,0.90
6,7,KitchenAid Stand Mixer,Home & Kitchen,Kitchen Appliances,KitchenAid,349.99,245.00,10.00
7,8,Cuisinart Coffee Maker,home & kitchen,Kitchen Appliances,Cuisinart,99.99,55.00,3.50
8,9,IKEA Malm Dresser,Home and Kitchen,Furniture,IKEA,179.99,85.00,3.50
9,10,Penguin Classics Collection,Books,Fiction,Penguin,49.99,27.50,2.00
10,11,The North Face Jacket,Sports & Outdoors,Jackets,The North Face,199.99,110.00,1.30
11,12,Nike Running Shoes,sports & outdoors,Shoes,Nike,129.99,65.00,0.70
12,13,LEGO Star Wars Set,Toys,Building Toys,LEGO,89.99,45.00,1.50
13,14,L'Oreal Revitalift Cream,Beauty,Skincare,L'Oreal,19.99,8.00,0.30
14,15,Apple MacBook Pro,Electronics,Laptops,Apple,-1599.99,1100.00,3.50
15,16,Bose QuietComfort 45,Electronics,Headphones,Bose,329.99,495.00,0.50
16,17,Hershey's Chocolate Assortment,Grocery,Snacks,Hershey's,15.99,7.00,1.00
17,18,Adidas Track Pants,Clothing,Pants,Adidas,45.99,23.00,0.60
18,19,Kindle Paperwhite,ELECTRONICS,E-Readers,Amazon,139.99,80.00,0.40
19,20,Dyson V11 Vacuum,HOME & KITCHEN,Appliances,Dyson,599.99,375.00,6.70
20,21,Outdoor Gas Grill,Home & Kitchen,Outdoor,Weber,299.99,165.00,25.00
21,22,Calvin Klein Men's Shirt,Apparel,Shirts,Calvin Klein,39.99,20.00,25.00
22,23,Coleman Camping Tent,Sports and Outdoors,Camping,Coleman,149.99,75.00,8.50
23,24,Mattel Barbie Dreamhouse,Toys,Dolls,Mattel,199.99,99.00,12.00
24,25,Neutrogena Face Wash,beauty,Skincare,Neutrogena,9.99,4.00,0.35
25,26,General Mills Cereal,Food,Breakfast,General Mills,4.99,1.80,0.90
26,27,Sony PlayStation 5,Electronics,Gaming,Sony,499.99,399.00,4.50
27,28,HP Wireless Printer,electronics,Printers,HP,129.99,85.00,15.00
28,29,Zara Maxi Dress,Clothing,Dresses,Zara,79.99,32.00,0.50
29,30,Columbia Winter Parka,Sports & Outdoors,Jackets,Columbia,249.99,150.00,3.20

In [78]:
df['product_id'].unique

<bound method Series.unique of 0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
25    26
26    27
27    28
28    29
29    30
Name: product_id, dtype: int64>

In [84]:
df.groupby('category')['price'].sum().sort_values(ascending = False)

category
Electronics            1429.97
electronics             929.98
Home & Kitchen          649.98
HOME & KITCHEN          599.99
ELECTRONICS             489.98
Sports & Outdoors       449.98
Toys                    289.98
Home and Kitchen        179.99
Clothing                150.97
Sports and Outdoors     149.99
sports & outdoors       129.99
home & kitchen           99.99
clothing                 59.99
Books                    49.99
Apparel                  39.99
Beauty                   19.99
Grocery                  15.99
beauty                    9.99
Food                      4.99
Name: price, dtype: float64