In [39]:
import pandas as pd
import numpy as np
df = pd.read_csv(r'C:\Users\ssrin\Workspace\Code\Upright_edu\wk8-customers.csv')

In [40]:
df

,customer_id,first_name,last_name,email,phone,address,city,state,zip_code,registration_date
0,1,James,Smith,james.smith@gmail.com,555-123-4567,123 Main St,New York,NY,10001,2021-03-15
1,2,Mary,Johnson,NaN,212.555.6789,456 Park Ave,New York,NY,10022,2020-11-02
2,3,John,Williams,jwilliams@yahoo.com,(555) 987-6543,789 Broadway,Los Angeles,California,90001-1234,2021-05-20
3,4,Patricia,Brown,pbrown@hotmail.com,5551234567,321 Elm St,Chicago,IL,60601,NaN
4,5,Robert,Jones,rjones23@gmail.com,555-987-3456,555 Pine St,Houston,TX,77002,2020-09-12
5,6,Jennifer,Miller,jmiller@outlook.com,NaN,898 Cedar Dr,Phoenix,AZ,85001,2021-02-28
6,7,Michael,Davis,mdavis@gmail.com,555.432.7654,742 Maple Ave,Philadelphia,PA,19103,2021-01-17
7,8,Linda,Garcia,lgarcia@yahoo.com,555 876 2345,953 Oak Ln,San Antonio,Texas,78205,2020-10-05
8,9,William,Rodriguez,wrodriguez@hotmail.com,5558889999,159 Washington Blvd,San Diego,CA,92101,2021-06-30
9,10,Elizabeth,Wilson,ewilson@gmail.com,(555) 333-2211,753 Lincoln Rd,Dallas,TX,75201,2020-08-22
10,11,David,Martinez,dmartinez@yahoo.com,555-111-3333,246 Jefferson Ave,San Jose,CA,95113,2021-04-09
11,12,Barbara,Anderson,NaN,555.444.9876,135 Madison St,Austin,TX,NaN,2020-12-27
12,13,Richard,Taylor,rtaylor@outlook.com,5552223333,864 Adams Ct,Jacksonville,FL,32202,2021-07-14
13,14,Susan,Thomas,sthomas45@gmail.com,NaN,579 Monroe Pl,Fort Worth,TX,76102,2020-07-18
14,15,Joseph,Hernandez,jhernandez@yahoo.com,555-777-8888,951 Jackson Dr,Columbus,OH,43215,2021-01-03
15,16,Jessica,Moore,jmoore@hotmail.com,555.666.1234,357 Tyler St,Charlotte,North Carolina,28202,NaN
16,17,Thomas,Martin,tmartin@gmail.com,(555) 444-5678,159 Polk Ave,San Francisco,CA,94102,2020-10-19
17,18,Sarah,Jackson,sjackson@yahoo.com,5557890123,753 Harrison Rd,Indianapolis,IN,46204,2021-03-01
18,19,Charles,Thompson,cthompson@outlook.com,555-321-6547,951 Van Buren St,Seattle,Washington,98101,2020-09-05
19,20,Karen,White,kwhite88@gmail.com,555.789.4561,357 Fillmore Dr,Denver,CO,80202,2021-05-12
20,21,Christopher,Lopez,clopez@yahoo.com,555 456 7890,159 Pierce Ave,Boston,MA,02108,2020-11-30
21,22,Nancy,Lee,nlee@hotmail.com,5559876543,753 Hayes Blvd,Portland,Oregon,97201,2021-02-14
22,23,Daniel,Gonzalez,dgonzalez@gmail.com,(555) 123-7890,951 Grant St,Las Vegas,NV,89101,2020-08-08
23,24,Margaret,Harris,mharris@yahoo.com,555-321-6789,357 Sherman Rd,Detroit,MI,48226,2021-04-25
24,25,Matthew,Clark,mclark@outlook.com,555.654.9870,159 Sheridan Dr,Nashville,TN,37201,NaN
25,26,Betty,Lewis,betty.lewis@gmail.com,5551597532,753 MacArthur Blvd,Baltimore,Maryland,21202,2020-07-01
26,26,Betty,Lewis,blewis23@gmail.com,555 159 7532,753 MacArthur Boulevard,Baltimore,MD,21202,2020-07-01
27,27,Steven,Robinson,srobinson@yahoo.com,555-951-7532,951 Hooker St,Louisville,KY,40202,2021-06-17
28,28,Dorothy,Walker,dwalker@hotmail.com,5553579514,357 Halsted Ave,Milwaukee,WI,53202,2020-09-30
29,29,Anthony,Perez,NaN,555.753.9512,159 Ashland Dr,Albuquerque,NM,87102,2021-01-28
30,30,Lisa,Hall,lhall@gmail.com,(555) 951-7530,753 Morgan St,Kansas City,MO,64101,2020-10-15

In [41]:
df.head()

,customer_id,first_name,last_name,email,phone,address,city,state,zip_code,registration_date
0,1,James,Smith,james.smith@gmail.com,555-123-4567,123 Main St,New York,NY,10001,2021-03-15
1,2,Mary,Johnson,NaN,212.555.6789,456 Park Ave,New York,NY,10022,2020-11-02
2,3,John,Williams,jwilliams@yahoo.com,(555) 987-6543,789 Broadway,Los Angeles,California,90001-1234,2021-05-20
3,4,Patricia,Brown,pbrown@hotmail.com,5551234567,321 Elm St,Chicago,IL,60601,NaN
4,5,Robert,Jones,rjones23@gmail.com,555-987-3456,555 Pine St,Houston,TX,77002,2020-09-12

In [42]:
df.describe()

       customer_id
count    31.000000
mean     15.838710
std       8.858505
min       1.000000
25%       8.500000
50%      16.000000
75%      23.500000
max      30.000000

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        31 non-null     int64
 1   first_name         31 non-null     str
 2   last_name          31 non-null     str
 3   email              28 non-null     str
 4   phone              29 non-null     str
 5   address            31 non-null     str
 6   city               31 non-null     str
 7   state              31 non-null     str
 8   zip_code           30 non-null     str
 9   registration_date  28 non-null     str
dtypes: int64(1), str(9)
memory usage: 2.6 KB

In [44]:
df.isnull().sum()

customer_id          0
first_name           0
last_name            0
email                3
phone                2
address              0
city                 0
state                0
zip_code             1
registration_date    3
dtype: int64

In [45]:
df['email']=df['email'].fillna(df['email'].mode())
df['phone']=df['phone'].fillna(df['phone'].mode())
df['zip_code']=df['zip_code'].ffill()
df['registration_date']=df['registration_date'].bfill()

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        31 non-null     int64
 1   first_name         31 non-null     str
 2   last_name          31 non-null     str
 3   email              30 non-null     str
 4   phone              31 non-null     str
 5   address            31 non-null     str
 6   city               31 non-null     str
 7   state              31 non-null     str
 8   zip_code           31 non-null     str
 9   registration_date  31 non-null     str
dtypes: int64(1), str(9)
memory usage: 2.6 KB

In [47]:
df['phone']=df['phone'].astype(dtype='object')
df['email']=df['email'].astype(dtype='object')
df['registration_date']=pd.to_datetime(df['registration_date'])

In [48]:
df['state']=df['state'].replace('North Carolina', 'NC')
df['state']=df['state'].replace('Texas', 'TX')
df['state']=df['state'].replace('California', 'CA')
df['state']=df['state'].replace('Washington', 'WA')
df['state']=df['state'].replace('Oregon', 'OR')
df['state']=df['state'].replace('Maryland', 'MA')

In [49]:
df.duplicated().sum()

np.int64(0)

In [50]:
df.drop_duplicates()

,customer_id,first_name,last_name,email,phone,address,city,state,zip_code,registration_date
0,1,James,Smith,james.smith@gmail.com,555-123-4567,123 Main St,New York,NY,10001,2021-03-15
1,2,Mary,Johnson,blewis23@gmail.com,212.555.6789,456 Park Ave,New York,NY,10022,2020-11-02
2,3,John,Williams,jwilliams@yahoo.com,(555) 987-6543,789 Broadway,Los Angeles,CA,90001-1234,2021-05-20
3,4,Patricia,Brown,pbrown@hotmail.com,5551234567,321 Elm St,Chicago,IL,60601,2020-09-12
4,5,Robert,Jones,rjones23@gmail.com,555-987-3456,555 Pine St,Houston,TX,77002,2020-09-12
5,6,Jennifer,Miller,jmiller@outlook.com,212.555.6789,898 Cedar Dr,Phoenix,AZ,85001,2021-02-28
6,7,Michael,Davis,mdavis@gmail.com,555.432.7654,742 Maple Ave,Philadelphia,PA,19103,2021-01-17
7,8,Linda,Garcia,lgarcia@yahoo.com,555 876 2345,953 Oak Ln,San Antonio,TX,78205,2020-10-05
8,9,William,Rodriguez,wrodriguez@hotmail.com,5558889999,159 Washington Blvd,San Diego,CA,92101,2021-06-30
9,10,Elizabeth,Wilson,ewilson@gmail.com,(555) 333-2211,753 Lincoln Rd,Dallas,TX,75201,2020-08-22
10,11,David,Martinez,dmartinez@yahoo.com,555-111-3333,246 Jefferson Ave,San Jose,CA,95113,2021-04-09
11,12,Barbara,Anderson,jmoore@hotmail.com,555.444.9876,135 Madison St,Austin,TX,95113,2020-12-27
12,13,Richard,Taylor,rtaylor@outlook.com,5552223333,864 Adams Ct,Jacksonville,FL,32202,2021-07-14
13,14,Susan,Thomas,sthomas45@gmail.com,555-777-8888,579 Monroe Pl,Fort Worth,TX,76102,2020-07-18
14,15,Joseph,Hernandez,jhernandez@yahoo.com,555-777-8888,951 Jackson Dr,Columbus,OH,43215,2021-01-03
15,16,Jessica,Moore,jmoore@hotmail.com,555.666.1234,357 Tyler St,Charlotte,NC,28202,2020-10-19
16,17,Thomas,Martin,tmartin@gmail.com,(555) 444-5678,159 Polk Ave,San Francisco,CA,94102,2020-10-19
17,18,Sarah,Jackson,sjackson@yahoo.com,5557890123,753 Harrison Rd,Indianapolis,IN,46204,2021-03-01
18,19,Charles,Thompson,cthompson@outlook.com,555-321-6547,951 Van Buren St,Seattle,WA,98101,2020-09-05
19,20,Karen,White,kwhite88@gmail.com,555.789.4561,357 Fillmore Dr,Denver,CO,80202,2021-05-12
20,21,Christopher,Lopez,clopez@yahoo.com,555 456 7890,159 Pierce Ave,Boston,MA,02108,2020-11-30
21,22,Nancy,Lee,nlee@hotmail.com,5559876543,753 Hayes Blvd,Portland,OR,97201,2021-02-14
22,23,Daniel,Gonzalez,dgonzalez@gmail.com,(555) 123-7890,951 Grant St,Las Vegas,NV,89101,2020-08-08
23,24,Margaret,Harris,mharris@yahoo.com,555-321-6789,357 Sherman Rd,Detroit,MI,48226,2021-04-25
24,25,Matthew,Clark,mclark@outlook.com,555.654.9870,159 Sheridan Dr,Nashville,TN,37201,2020-07-01
25,26,Betty,Lewis,betty.lewis@gmail.com,5551597532,753 MacArthur Blvd,Baltimore,MA,21202,2020-07-01
26,26,Betty,Lewis,blewis23@gmail.com,555 159 7532,753 MacArthur Boulevard,Baltimore,MD,21202,2020-07-01
27,27,Steven,Robinson,srobinson@yahoo.com,555-951-7532,951 Hooker St,Louisville,KY,40202,2021-06-17
28,28,Dorothy,Walker,dwalker@hotmail.com,5553579514,357 Halsted Ave,Milwaukee,WI,53202,2020-09-30
29,29,Anthony,Perez,NaN,555.753.9512,159 Ashland Dr,Albuquerque,NM,87102,2021-01-28
30,30,Lisa,Hall,lhall@gmail.com,(555) 951-7530,753 Morgan St,Kansas City,MO,64101,2020-10-15

In [51]:
df.dropna(inplace = True)

In [52]:
df

,customer_id,first_name,last_name,email,phone,address,city,state,zip_code,registration_date
0,1,James,Smith,james.smith@gmail.com,555-123-4567,123 Main St,New York,NY,10001,2021-03-15
1,2,Mary,Johnson,blewis23@gmail.com,212.555.6789,456 Park Ave,New York,NY,10022,2020-11-02
2,3,John,Williams,jwilliams@yahoo.com,(555) 987-6543,789 Broadway,Los Angeles,CA,90001-1234,2021-05-20
3,4,Patricia,Brown,pbrown@hotmail.com,5551234567,321 Elm St,Chicago,IL,60601,2020-09-12
4,5,Robert,Jones,rjones23@gmail.com,555-987-3456,555 Pine St,Houston,TX,77002,2020-09-12
5,6,Jennifer,Miller,jmiller@outlook.com,212.555.6789,898 Cedar Dr,Phoenix,AZ,85001,2021-02-28
6,7,Michael,Davis,mdavis@gmail.com,555.432.7654,742 Maple Ave,Philadelphia,PA,19103,2021-01-17
7,8,Linda,Garcia,lgarcia@yahoo.com,555 876 2345,953 Oak Ln,San Antonio,TX,78205,2020-10-05
8,9,William,Rodriguez,wrodriguez@hotmail.com,5558889999,159 Washington Blvd,San Diego,CA,92101,2021-06-30
9,10,Elizabeth,Wilson,ewilson@gmail.com,(555) 333-2211,753 Lincoln Rd,Dallas,TX,75201,2020-08-22
10,11,David,Martinez,dmartinez@yahoo.com,555-111-3333,246 Jefferson Ave,San Jose,CA,95113,2021-04-09
11,12,Barbara,Anderson,jmoore@hotmail.com,555.444.9876,135 Madison St,Austin,TX,95113,2020-12-27
12,13,Richard,Taylor,rtaylor@outlook.com,5552223333,864 Adams Ct,Jacksonville,FL,32202,2021-07-14
13,14,Susan,Thomas,sthomas45@gmail.com,555-777-8888,579 Monroe Pl,Fort Worth,TX,76102,2020-07-18
14,15,Joseph,Hernandez,jhernandez@yahoo.com,555-777-8888,951 Jackson Dr,Columbus,OH,43215,2021-01-03
15,16,Jessica,Moore,jmoore@hotmail.com,555.666.1234,357 Tyler St,Charlotte,NC,28202,2020-10-19
16,17,Thomas,Martin,tmartin@gmail.com,(555) 444-5678,159 Polk Ave,San Francisco,CA,94102,2020-10-19
17,18,Sarah,Jackson,sjackson@yahoo.com,5557890123,753 Harrison Rd,Indianapolis,IN,46204,2021-03-01
18,19,Charles,Thompson,cthompson@outlook.com,555-321-6547,951 Van Buren St,Seattle,WA,98101,2020-09-05
19,20,Karen,White,kwhite88@gmail.com,555.789.4561,357 Fillmore Dr,Denver,CO,80202,2021-05-12
20,21,Christopher,Lopez,clopez@yahoo.com,555 456 7890,159 Pierce Ave,Boston,MA,02108,2020-11-30
21,22,Nancy,Lee,nlee@hotmail.com,5559876543,753 Hayes Blvd,Portland,OR,97201,2021-02-14
22,23,Daniel,Gonzalez,dgonzalez@gmail.com,(555) 123-7890,951 Grant St,Las Vegas,NV,89101,2020-08-08
23,24,Margaret,Harris,mharris@yahoo.com,555-321-6789,357 Sherman Rd,Detroit,MI,48226,2021-04-25
24,25,Matthew,Clark,mclark@outlook.com,555.654.9870,159 Sheridan Dr,Nashville,TN,37201,2020-07-01
25,26,Betty,Lewis,betty.lewis@gmail.com,5551597532,753 MacArthur Blvd,Baltimore,MA,21202,2020-07-01
26,26,Betty,Lewis,blewis23@gmail.com,555 159 7532,753 MacArthur Boulevard,Baltimore,MD,21202,2020-07-01
27,27,Steven,Robinson,srobinson@yahoo.com,555-951-7532,951 Hooker St,Louisville,KY,40202,2021-06-17
28,28,Dorothy,Walker,dwalker@hotmail.com,5553579514,357 Halsted Ave,Milwaukee,WI,53202,2020-09-30
30,30,Lisa,Hall,lhall@gmail.com,(555) 951-7530,753 Morgan St,Kansas City,MO,64101,2020-10-15

In [53]:
df['customer_id']=df['customer_id'].unique

In [64]:
df.groupby('state')['city'].sum()

state
AZ                                      Phoenix
CA    Los AngelesSan DiegoSan JoseSan Francisco
CO                                       Denver
FL                                 Jacksonville
IL                                      Chicago
IN                                 Indianapolis
KY                                   Louisville
MA                              BostonBaltimore
MD                                    Baltimore
MI                                      Detroit
MO                                  Kansas City
NC                                    Charlotte
NV                                    Las Vegas
NY                             New YorkNew York
OH                                     Columbus
OR                                     Portland
PA                                 Philadelphia
TN                                    Nashville
TX     HoustonSan AntonioDallasAustinFort Worth
WA                                      Seattle
WI                                    Milwaukee
Name: city, dtype: str